spring:
 datasource:
  url: jdbc:mysql://localhost:3306/nace?createDatabaseIfNotExist=true
  username: root
  password: 
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate.ddl-auto: update
---
spring:
    mvc:
      pathmatch:
            matching-strategy: ant_path_matcher